// AUTO-GENERATED by npm run update:houses. Do not edit by hand.
export const houseAssets = [
  { src: "assets/generated/houses/house1.png", label: "Casa 1", w: 991, h: 1012 },
  { src: "assets/generated/houses/house2.png", label: "Casa 2", w: 1143, h: 772 },
  { src: "assets/generated/houses/house3.png", label: "Casa 3", w: 1348, h: 707 },
  { src: "assets/generated/houses/house4.png", label: "Casa 4", w: 654, h: 1090 },
  { src: "assets/generated/houses/house5.png", label: "Casa 5", w: 1186, h: 616 },
  { src: "assets/generated/houses/house6.png", label: "Casa 6", w: 1193, h: 499 },
  { src: "assets/generated/houses/house8.png", label: "Casa 8", w: 1103, h: 908 },
  { src: "assets/generated/houses/house9.png", label: "Casa 9", w: 1111, h: 984 },
  { src: "assets/generated/houses/house10.png", label: "Casa 10", w: 1166, h: 809 },
  { src: "assets/generated/houses/house11.png", label: "Casa 11", w: 1149, h: 771 },
  { src: "assets/generated/houses/house12.png", label: "Casa 12", w: 1254, h: 1254 },
];
