// AUTO-GENERATED by npm run update:objects. Do not edit by hand.
export const objectAssets = [
  { src: "assets/generated/objects/object1.png", label: "Objeto 1", w: 1448, h: 1086 },
  { src: "assets/generated/objects/object2.png", label: "Objeto 2", w: 941, h: 1288 },
  { src: "assets/generated/objects/object3.png", label: "Objeto 3", w: 1031, h: 1049 },
  { src: "assets/generated/objects/object4.png", label: "Objeto 4", w: 218, h: 1046 },
  { src: "assets/generated/objects/object5.png", label: "Objeto 5", w: 916, h: 968 },
  { src: "assets/generated/objects/object6.png", label: "Objeto 6", w: 976, h: 886 },
  { src: "assets/generated/objects/object7.png", label: "Objeto 7", w: 893, h: 931 },
];
