// AUTO-GENERATED by npm run update:maps. Do not edit by hand.
export const scenarioLayouts = {
  "plaza": {
    "ground": [
      "#595959",
      "#4f4f4f",
      "#656565"
    ],
    "paths": "#615d58",
    "pathRects": [],
    "plazas": [],
    "objects": [
      [
        855,
        1720,
        71,
        64,
        5,
        1
      ],
      [
        1490,
        1567,
        200,
        150,
        0,
        1
      ]
    ],
    "spawn": {
      "player": [
        1098,
        1662
      ],
      "jarramplas": [
        1760,
        930
      ],
      "target": [
        1341,
        1076
      ]
    },
    "houses": [
      [
        735,
        1000,
        412,
        300,
        11,
        1
      ],
      [
        1193,
        996,
        404,
        300,
        13,
        1
      ],
      [
        1635,
        994,
        412,
        300,
        14,
        1
      ],
      [
        2068,
        988,
        412,
        300,
        14,
        1
      ]
    ]
  }
};
