import { PLAYER_MAX_TURNIPS } from "./constants.js";

export const assets = {
  loaded: 0,
  total: 0,
  images: {},
  jarramplas: [],
  backgrounds: [],
};

export const state = {
  mode: "loading",
  gameType: "timed",
  difficulty: "day19Morning",
  playerIndex: 0,
  scenarioIndex: 0,
  jarramplasIndex: 0,
  tutorialNextScreen: "type",
  activeChallenge: null,
  w: 0,
  h: 0,
  camera: { x: 0, y: 0 },
  player: null,
  jarramplas: null,
  people: [],
  bystanders: [],
  piles: [],
  turnips: [],
  impacts: [],
  floaters: [],
  particles: [],
  obstacles: [],
  joystick: { active: false, pointerId: null, x: 0, y: 0, dx: 0, dy: 0 },
  score: 0,
  combo: 1,
  comboHits: 0,
  life: 100,
  timeLeft: 60,
  turnipsLeft: PLAYER_MAX_TURNIPS,
  jarramplasHealth: 100,
  throws: 0,
  hits: 0,
  peopleHits: 0,
  elapsed: 0,
  last: 0,
  startedAt: 0,
  ended: false,
  touchCooldown: 0,
};
